# GoReleaser configuration for Line Cook CLI
# Documentation: https://goreleaser.com

version: 2

project_name: lc

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: lc
    main: ./cmd/lc
    binary: lc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/smileynet/line-cook/internal/cli.Version={{.Version}}
      - -X github.com/smileynet/line-cook/internal/cli.Commit={{.Commit}}
      - -X github.com/smileynet/line-cook/internal/cli.BuildDate={{.Date}}

archives:
  - id: lc
    builds:
      - lc
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

brews:
  - name: lc
    repository:
      owner: smileynet
      name: homebrew-tools
    folder: Formula
    homepage: https://github.com/smileynet/line-cook
    description: "Line Cook CLI - Workflow orchestration for AI coding assistants"
    license: MIT
    skip_upload: auto
    test: |
      system "#{bin}/lc", "version"
    install: |
      bin.install "lc"

nfpms:
  - id: lc
    package_name: lc
    vendor: smileynet
    homepage: https://github.com/smileynet/line-cook
    maintainer: smileynet
    description: "Line Cook CLI - Workflow orchestration for AI coding assistants"
    license: MIT
    formats:
      - deb
      - rpm

release:
  github:
    owner: smileynet
    name: line-cook
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
